stages:
  - build
  - test

cache:
  paths:
    - back/.m2/repository/
    - back/target/
    - front/node_modules/

build_backend:
  image: maven:3.8.4
  stage: build
  only:
    refs:
      - master
      - demo
      - /^TASK-.*$/
  script:
    - cd back
    - mvn clean install

build_frontend:
  image: node:16-alpine
  stage: build
  only:
    refs:
      - master
      - demo
      - /^TASK-.*$/
  script:
    - cd front
    - npm ci
    - npm run build

test:
  image: maven:3.8.4
  stage: test
  only:
    refs:
      - master
      - demo
      - /^TASK-.*$/
  script:
    - cd back
    - mvn test
